### ISSUE TITLE
Use alternative workaround for cafile issue with node v4

### ISSUE THREAD

**Issue by springmeyer** [mapbox/ci-scripts#2]
I think we can remove https://github.com/mapbox/ci-scripts/blob/master/node/ci-cpp.bat#L38-L46. This is because I found that this problem can be worked around by upgrading node-gyp. See https://github.com/mapbox/node-pre-gyp/issues/209#issuecomment-307641388

@BergWerkGIS can you please:

  - Confirm that upgrading node-gyp (which should already be being done in the package.json) works around this problem in the repos you've been testing?
  - If so we'll plan to keep node-gyp upgrade in place for node v4 (and not just for node v0.10.x), and this should be documented in the readme for co-scripts

**Comment by wilhelmberg** [comment]
Removed `cafile` workaround: https://github.com/mapbox/ci-scripts/commit/47726e21db06eda083908165b1d85f4a46d23e19

> Confirm that upgrading node-gyp (which should already be being done in the package.json) works around this problem in the repos you've been testing?

All repositories I've been testing are ✅ on AppVeyor (`node-gdal` still running as of now).

> If so we'll plan to keep node-gyp upgrade in place for node v4 (and not just for node v0.10.x), and this should be documented in the readme for co-scripts

done: https://github.com/mapbox/ci-scripts/tree/master/node
